### PR TITLE
Add whitelist and blacklist preferences for application blur

### PR DESCRIPTION
**Pull request by aunetx**

### CODE REVIEW

**Comment by aunetx** [comment]
Now simply needs the `enable all` behaviour extension-side

**Comment by aunetx** [comment]
Will close #198 and #197

**Comment by CorvetteCole** [comment]
this is awesome! I'm still working on an applications menu type search menu, we can use that to validate window names etc.

**Review by CorvetteCole — COMMENTED** [review]
Looks great! I'll give it a test in a few

**Review by CorvetteCole — APPROVED** [review]
seems to work as expected looks good to me!

**Comment by aunetx** [comment]
Thanks :)

**Comment by CorvetteCole** [comment]
@aunetx I just realized that it seems a blacklist was enabled by default with blurring all applications a default option. Can you double check to make sure that isn't true? wouldn't want to reduce performance for all users by default

**Comment by aunetx** [comment]
@CorvetteCole uh oh, nice catch! That's ofc not what I intended; just fixed this (I am working on multiple panels support in the same time so I will commit this asap)

**Pull request merged**
