### PR TITLE
Port to GNOME 47

### LINKED ISSUE #620: Gnome 47 issues
`TypeError: (intermediate value).Color is undefined`
This is all i got so far

### PR DESCRIPTION
**Pull request by DaPigGuy**
Fixes #620

### CODE REVIEW

**Comment by fjadron** [comment]
it worked after i added  import Cogl from 'gi://Cogl';

**Comment by DaPigGuy** [comment]
Thanks for testing! Somehow that was missed in the commit 😅

**Comment by aunetx** [comment]
Hello, thanks a lot for this! Do you know if it should work with GNOME 46 too? (so that I can keep compatibility)

**Comment by aunetx** [comment]
Thanks for the modification! I'm merging this right now, because I guess I won't push another version to extensions.gnome.org before GNOME 47 beta is released :)

**Comment by aunetx** [comment]
Uh, well if you did put it in draft maybe you wanted to do other changes?

**Comment by DaPigGuy** [comment]
Since 47.beta is out now and everything still works, feel free to merge now :)

**Comment by aunetx** [comment]
OK perfect, thanks a lot!

**Pull request merged**
