### PR TITLE
Port to GNOME 45

### LINKED ISSUE #466: [Feature Request] Add GNOME 45 Support
GNOME 45 is in beta now, Please add support for it to ensure compatibility with the latest version of GNOME and provide users with access to new features and improvements.

resources: [gjs.guide/extensions/upgrading/gnome-shell-45.html](https://gjs.guide/extensions/upgrading/gnome-shell-45.html)

### PR DESCRIPTION
**Pull request by DaPigGuy**
Supersedes #470, closes #466

**Issues**
- [x] Windows in the current workspace appears in the blurred background
  - This is very obvious with a maximized window

### CODE REVIEW

**Comment by RyzenDew** [comment]
image
loads of bugs so far

-  Blur isn't fully applied on the panel and it's very buggy image


- The dock is blurred wrong and now it never blends in proper 
image

**Comment by aunetx** [comment]
@RyzenDew I can't reproduce the topbar bug, and the dock bug should be resolved later I guess (it never entirely worked tbh...)

@DaPigGuy thank you very very much! It works quite well with gnome os nightly, but I can reproduce the bug you described...

I kind of like this behaviour, but of course it should not be -- but I guess it would require a rewrite of how blur-my-shell it fetching the overview background, as the gnome team appears to now alter the background depending of the windows positions on top of it.

I guess it is time finally load the background ourselves, however I don't know how to do it to be honest...

PS: thank you veryyyy much for the way you included the templates in the preferences! I did not have any idea how to do it, so you saved me a lot of time (as I was preparing to rewrite entirely the way I imported UI files)

**Comment by RyzenDew** [comment]
> @RyzenDew I can't reproduce the topbar bug, and the dock bug should be resolved later I guess (it never entirely worked tbh...)
> 
> @DaPigGuy thank you very very much! It works quite well with gnome os nightly, but I can reproduce the bug you described...
> 
> I kind of like this behaviour, but of course it should not be -- but I guess it would require a rewrite of how blur-my-shell it fetching the overview background, as the gnome team appears to now alter the background depending of the windows positions on top of it.
> 
> I guess it is time finally load the background ourselves, however I don't know how to do it to be honest...
> 
> PS: thank you veryyyy much for the way you included the templates in the preferences! I did not have any idea how to do it, so you saved me a lot of time (as I was preparing to rewrite entirely the way I imported UI files)

I was able to reproduce it on 4 machines so it’s definitely a bug and the dock being that way is new as they redid the dock a bit if you compared before to now which i did in my videos covering gnome 45

**Comment by DaPigGuy** [comment]
@RyzenDew I am also unable to reproduce the issue with the top panel blur. Make sure to try without other extensions.

**Comment by RyzenDew** [comment]
I tried without others no difference Sent from my iPhoneOn Sep 18, 2023, at 10:17 PM, DaPigGuy ***@***.***> wrote:﻿
@RyzenDew I am also unable to reproduce the issue with the top panel blur. Make sure to try without other extensions.

**Comment by RyzenDew** [comment]
370330750_18380707711046631_8739468651387267063_n-enhance-4x
it only happens with this wallpaper which is weird

**Comment by RyzenDew** [comment]
image
another bug if application blur is enabled all by default the background blurs on the desktop

**Comment by DaPigGuy** [comment]
@RyzenDew Please try the latest changes

**Comment by Titaniumtown** [comment]
PR works great for me, no issues so far. Will report back if I find anything (Gnome 45, Fedora Silverblue 39)

**Comment by RyzenDew** [comment]
> @RyzenDew Please try the latest changes

So the panel blur is fixed but the gjs issue is still there when application blur is enabled by default

**Comment by DaPigGuy** [comment]
@RyzenDew I am unable to reproduce the application blur issue.

**Comment by RyzenDew** [comment]
just updated to gnome 45 final release on arch and application issue is fixed

**Comment by KUPOinyourWINDOW** [comment]
the latest version of your commit fixes the top panel blur and background application appearing in overview for me on fedora 39 beta, thank you very much <3

**Comment by aunetx** [comment]
Thank you @DaPigGuy, you're really good! I would have taken days to fix this issue to be honest...

I merge this, and will push it to extensions.gnome.org this afternoon!

**Pull request merged**
