### PR TITLE
Add support for Gnome 40

### PR DESCRIPTION
**Pull request by aunetx**
See #24 for the issue

To this moment, the only big issue that remains is #31, but the extension is stable on gnome 40 if this option is temporarily disabled.

### CODE REVIEW

**Review by CorvetteCole — APPROVED** [review]
I took a look through these changes, from an extension reviewers perspective everything looks good!

**Comment by aunetx** [comment]
Thanks a lot, do you think it is a good idea to wait for #31 to be resolved before merging this?
I talked to gnome devs yesterday night, but did not find a real solution to it (from what I understood, I would need to extend the `Shell.BlurEffect` actor, and modify its paint vfunc... but that's still some witch language for me, my 'paint' signal workaround was simpler) :)

**Comment by aunetx** [comment]
@CorvetteCole I pushed this to extensions.gnome.org, and the support for dash-to-dock seemed good enough to merge this pull request :)

**Comment by CorvetteCole** [comment]
I approved the extension update! I think I'll rebase my branch on to a new branch called application-blur or something. About the vfunc, I remember being told about that and trying to figure it out but I got stuck in the past. I'm going to take a look at it again, but it seems like some dark voodoo witchcraft to me

**Comment by aunetx** [comment]
Thanks a lot, that's really cool to be able to update the extension so quickly :)
And of course for your branch, do what you need ^^

For the vfunc, I think I kind of understand the principle, but I really don't know how to implement it... For the moment I will add an option to have static blur for the top panel instead of dynamic blur, so there is no more artifact (and it does not change a lot of things, excepted if the use uses something like hide-my-topbar, but that's okay for the moment)

**Pull request merged**
