### PR TITLE
Add effect to emit 'paint' signal

### LINKED ISSUE #31: "no artefacts" option makes the extension crash
See https://redd.it/muxj77 for more infos

### PR DESCRIPTION
**Pull request by aunetx**
I successfully added the effect to fix #31, and it works great!
I tested it for the panel, it works as great as the ancient 'paint' signal (so there are still some artefacts, due to windows shadows...).

We may need a way to instantly add this effect and connect it, keep track of it and maybe clean it afterwards? Just like we do for the connected signals, it would simplify the design a bit.

### CODE REVIEW

**Comment by CorvetteCole** [comment]
I think I understand what you mean, but it looks like you are already adding the connection to that modules connection object. What more did you have in mind?

**Comment by aunetx** [comment]
What I was thinking about is simply that, when we remove the blur effect from the actor, with this method we will need to remove the `EmitPaintSignal` effect too (or it could be duplicated, or cause errors/overhead...)

So I was thinking about a method very similar to the one in connections.js, but maybe adapted to use this thing?

**Comment by CorvetteCole** [comment]
oh that's an interesting point, we don't want to needlessly emit extra signals. I'm not sure how we would implement this, but I think it is definitely a good idea. Maybe a PaintSignals.js class. Did you want to code that or should I put it on my to-do?

**Comment by aunetx** [comment]
Yeah maybe a dedicated class... Will you use this effect a lot for #39? If yes, this should definitively be added, but if not maybe just keeping track and removing the effects within the extension (for panel and overview) could be enough...

Anyway, if you want to work on this you can do it! And if not I will do this in some days/weeks anyway :)

**Comment by CorvetteCole** [comment]
It is pretty essential for #39. Artifacts on the blur effect of windows are really common since they are often over other actor shadows and moved around a lot. So will definitely be used there! I'm not going to start working on the class yet since I am pretty busy at the moment, but I will let you know before I do if I get to it first so we don't duplicate efforts :)

**Comment by aunetx** [comment]
I'll start to see what I can do about the paint signal :)

This is a good idea, it may be hard to keep track of everything else! Would you like to try to do this?

**Comment by aunetx** [comment]
I think this is good enough to be merged! But I'll wait for your review first, don't want to merge it if the model is not adapted to #39 :)

By the way, if you have dash-to-dock, you can test it with this PR, I did not test it enough because I don't have it installed... But it should be ok though!

**Comment by aunetx** [comment]
I will try to entirely remove artefacts BTW, I think that I have a very hacky solution (being to just track windows, and update the panel blur when they are moved... because their shadow is still creating artefacts, so I may be better with this).

**Comment by CorvetteCole** [comment]
sorry for such a late response. I  started a new internship only a few days ago and have been very very busy with it and moving. I'm going to be spending my weekends working on this again after the next two where I will be away. sorry again

**Review by CorvetteCole — APPROVED** [review]
I like these changes and think this is a pretty good way of handling things. A great workaround

**Comment by aunetx** [comment]
Cool thanks for the review, will merge this right now :)

And don't worry I really understand for the delay! I'm not very focused on the extension too, feel free not to answer for as long as you want :)

**Pull request merged**
